project:
  type: website
  output-dir: docs

lang: ru

website:
  repo-url: https://github.com/ver-qua/knowlage
  repo-branch: master
  repo-link-target: "_blank"
  repo-actions: [source, issue, edit]

  page-navigation: true

  title: "Учения"

  navbar:
    left:
      - text: "Дома"
        href: index.qmd
      - text: "Конспекты"
        href: Lecture_notes/index.qmd
      - text: "О этом"
        href: about.qmd

  sidebar:
    - title: "Конспекты"
      collapse-level: 3
      contents:
          - section: "Конспекты"
            href: Lecture_notes/index.qmd
            contents: 
              - section: "Линейная Алгебра"
                href: Lecture_notes/LinearAlgebra/index.qmd
                contents: 
                  - Lecture_notes/LinearAlgebra/P20_Several_real_variables_function.qmd
                  - Lecture_notes/LinearAlgebra/P21_SRVF_differentiation.qmd
                  - Lecture_notes/LinearAlgebra/P22_Rn_to_Rm_differentiation.qmd

              - section: "Диффуры"
                href: Lecture_notes/DifferentialEquations/index.qmd
                contents: 
                  - Lecture_notes/DifferentialEquations/P1_ODE_General_concepts.qmd

              - section: "Матанализ"
                href: Lecture_notes/Calculus/index.qmd
                contents: 
                  - Lecture_notes/Calculus/PX_integration_methods.qmd
                  - Lecture_notes/Calculus/PX_definite_integral.qmd

              - section: "Физика"
                href: Lecture_notes/Physics/index.qmd
                contents:
                  - section: "Электростатика"
                    href: "Lecture_notes/Physics/Electrostatics/index.qmd"
                    contents: 
                      - Lecture_notes/Physics/Electrostatics/electric_feild.qmd
                      - Lecture_notes/Physics/Electrostatics/gauss_theorem.qmd
                      - Lecture_notes/Physics/Electrostatics/Coulombs_law.qmd
                      - Lecture_notes/Physics/Electrostatics/electric_charge.qmd
                      - Lecture_notes/Physics/Electrostatics/electric_potential.qmd

                  - section: "Электрические цепи"
                    href: "Lecture_notes/Physics/ElectricCircuits/index.qmd"
                    contents: 
                      - Lecture_notes/Physics/ElectricCircuits/Transition_processes_L_C.qmd
                      - Lecture_notes/Physics/ElectricCircuits/RLC_circuit.qmd

format:
  html:
    toc: true
    toc-expand: true
    toc-depth: 5

    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem

    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]

    css: styles.css
