project:
  type: website
  output-dir: docs

lang: ru

website:
  repo-url: https://github.com/ver-qua/knowlage
  repo-branch: master
  repo-link-target: "_blank"
  repo-actions: [source, issue, edit]

  page-navigation: true

  title: "Учения"

  navbar:
    left:
      - text: "Дома"
        href: index.qmd
      - text: "Конспекты"
        href: Lecture_notes/index.qmd
      - text: "О этом"
        href: about.qmd

  sidebar:
    - title: "Конспекты"
      collapse-level: 5
      contents:
          - section: "📦Конспекты"
            href: Lecture_notes/index.qmd
            contents: 
              - section: "🗓️Линейная Алгебра"
                href: Lecture_notes/LinearAlgebra/index.qmd
                contents: 
                  - Lecture_notes/LinearAlgebra/P20_Several_real_variables_function.qmd
                  - Lecture_notes/LinearAlgebra/P21_SRVF_differentiation.qmd
                  - Lecture_notes/LinearAlgebra/P22_Rn_to_Rm_differentiation.qmd

              - section: "🏎️Диффуры"
                href: Lecture_notes/DifferentialEquations/index.qmd
                contents: 
                  - Lecture_notes/DifferentialEquations/P1_ODE_General_concepts.qmd

              - section: "📈Матанализ"
                href: Lecture_notes/Calculus/index.qmd
                contents: 
                  - Lecture_notes/Calculus/p1_complex_numbers.qmd
                  - Lecture_notes/Calculus/PX_integration_methods.qmd
                  - Lecture_notes/Calculus/PX_definite_integral.qmd

              - section: "🌍Физика"
                href: Lecture_notes/Physics/index.qmd
                contents:
                  - section: "🔋Электростатика"
                    href: "Lecture_notes/Physics/Electrostatics/index.qmd"
                    contents: 
                      - Lecture_notes/Physics/Electrostatics/P1_electric_feild.qmd
                      - Lecture_notes/Physics/Electrostatics/P2_gauss_theorem.qmd
                      - Lecture_notes/Physics/Electrostatics/P3_Coulombs_law.qmd
                      - Lecture_notes/Physics/Electrostatics/P4_electric_charge.qmd
                      - Lecture_notes/Physics/Electrostatics/P5_electric_potential.qmd
                      - Lecture_notes/Physics/Electrostatics/P6_electric_dipole.qmd
                      - Lecture_notes/Physics/Electrostatics/P7_electric_capacity.qmd
                      - Lecture_notes/Physics/Electrostatics/P8_capacitors.qmd
                      - Lecture_notes/Physics/Electrostatics/P9_energy_of_electrostatic_feild.qmd
                      - Lecture_notes/Physics/Electrostatics/P10_el_stat_eng_diffform.qmd

                  - section: "⚡Постоянный ток"
                    href: Lecture_notes/Physics/DirectCurrent/index.qmd
                    contents: 
                      - Lecture_notes/Physics/DirectCurrent/p1_direct_current.qmd
                      - Lecture_notes/Physics/DirectCurrent/p2_Ohms_law.qmd
                      - Lecture_notes/Physics/DirectCurrent/p3_Joule_Lenz_law.qmd
                      - Lecture_notes/Physics/DirectCurrent/p4_Drudus_Lorenz_theory_disaster.qmd
                      - Lecture_notes/Physics/DirectCurrent/p5_electromotive_force.qmd

                  - section: "🔗Электрические цепи"
                    href: "Lecture_notes/Physics/ElectricCircuits/index.qmd"
                    contents: 
                      - Lecture_notes/Physics/ElectricCircuits/Transition_processes_L_C.qmd
                      - Lecture_notes/Physics/ElectricCircuits/RLC_circuit.qmd

format:
  html:
    html-math-method: 
      method: mathjax
      
    toc: true
    toc-expand: true
    toc-depth: 5

    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem

    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]

    css: styles.css
