---
title: "Параграф I: Обыкновенные Дифференциальные Уравнения. Общие Понятия"
---

::: {layout-ncol="2"}
Уравнение вида:
$$
F(x, y, y') = 0
$$

- $F$ -- функция трёх переменных:
- $x$ -- независимая переменная
- $y$ -- искомая функция
- $y'$ -- производная искомой функции
:::
Называется **О**быкновенным **Д**ифференциальным **У**равнением **П**ервого **П**орядка (**ОДУ ПП**).
Например:
$$ x(y)^3 + 3\sin(2x-y') = 0 $$

#### Определение 1: Разрешенный вид ОДУ
Чаще всего встречается вид ОДУ ПП, называемый разрешённым относительно первой производной:
$$
y' = f(x,y)
$$

где $f: D \subset \mathbb{R}^2 \rightarrow \mathbb{R}$ и чаще всего $D$ имеет вид: $D = \langle a,b \rangle \times \langle c,d \rangle$(прямое произведение интервалов, где $\langle \dots \rangle$ означает промежуток с несущественной включённостью границ).

#### Определение 2: Решение ОДУ
Решением ОДУ ПП называется функция $y = y(x)$, заданная и дифференцируемая на некотором интервале $(\alpha, \beta)$ такая, что:
$$
\forall x \in (\alpha, \beta) \quad (x, y(x)) \in D \quad \text{и} \quad y'(x) \equiv f(x, y(x))
$$

График решения называется интегральной кривой. Из геометрического смысла следует, что угловой коэффициент касательной к интегральной кривой в точке $(x, y(x))$ равен $f(x, y(x))$.

#### Пример 1

::: {layout-ncol="2"}
Уравнение:
$$
y' = \sin(x)
$$
Решение:
$$
y = -\cos(x) + C
$$

Уравнение:
$$
y' = a y
$$
Решение:
$$
y = C e^{a x}
$$
Проверка:
$$
y' = C a e^{a x} = a y
$$
:::


#### Определение 3: Общее и частное решения
Функция 
$$
y = y(x, C)
$$

где $C$ -- произвольная постоянная, являющаяся при каждом $C$ решением ОДУ ПП, называется общим решением. Решение при конкретном $C$ называется частным.\
Часто решение получается в неявном виде:
$$
\phi(x,y, C) = 0
$$

Функция $\phi(x,y,C)$ называется интегралом ОДУ ПП.

#### Определение 4: Задача Коши
Пусть даны $x_0 \in \langle a,b \rangle$, $y_0 \in \langle c,d \rangle$ (или $(x_0,y_0) \in D \subset \mathbb{R}^2$). Условие:
$$
y(x_0) = y_0
$$

Называется начальным условием. Нахождение решения ОДУ, удовлетворяющего начальному условию, называется задачей Коши:
$$
\begin{cases}
y' = f(x,y) \\
y(x_0) = y_0
\end{cases}
$$

#### Пример 2
Задача Коши:
$$
\begin{cases}
y' = a y \\
y(x_0) = y_0
\end{cases}, \quad D = \mathbb{R} \times \mathbb{R}
$$

Решение:

1. Общее решение: $y = Ce^{a x}$
2. Находим $C$ из начального условия: $y_0 = Ce^{a x_0} \implies C = y_0 e^{-a x_0}$
3. Частное решение: $y = y_0 e^{a(x-x_0)}$

Итак: [существует единственное решение задачи Коши.]{.underline}