---
title: "Параграф XX: Функции нескольких переменных"
---
`Лекция от 03.02.2025`


#### Определение 1: функцией $n$ вещественных переменных.

##### 1. Если $X \subset \mathbb{R}^n$ и $Y \subset \mathbb{R}$
В этом случае $f$ называется функцией $n$ вещественных переменных и обозначения таковы:

::: {layout-ncol=2}
Переменная:
$$
\forall \vec{x} =
\begin{pmatrix}
x_1 \\
\vdots \\
x_n
\end{pmatrix}
\in X$ 
$$

Значение:
$$
f \left( \vec{x} \right),f \left(  x_1, x_2, \dots , x_n  \right)
$$

:::

Чаще всего вместо вектора $\vec{x}$, его называют точкой $n$ мерного пространства.

::: {layout-ncol="2"}

| В случае $\mathbb{R}^2$:
|	Tочка $M \left( x,  y \right)$ и $f \left( x, y \right)$, $f \left( M \right)$

| В случае $\mathbb{R}^3$:
|	Tочка $M \left( x, y, z \right)$ и $f \left( x, y, z \right)$, $f \left( M \right)$

:::

| 

##### 2. Если $X \subset \mathbb{R}^n$ и $Y \subset \mathbb{R}^m$

::: {layout-ncol="2"}

Функцию называют из $\mathbb{R}^n$ в $\mathbb{R}^m$	
$$
\vec f \left( \vec{x} \right) = 
\begin{pmatrix}
f_1 \left( \vec{x} \right) \\
f_2 \left( \vec{x} \right) \\
\vdots \\
f_n \left( \vec{x} \right) 
\end{pmatrix}
\in  \mathbb{R}^m
$$

Каждая $f_k$ - координата функции $\vec f$ и $f_k: X \to \mathbb{R}$, $k = 1, 2, \dots , m$
$$
f = 
\begin{pmatrix}
f_1 \\
f_2  \\
\vdots \\
f_n 
\end{pmatrix}
$$

:::

#### Определение 2: Окрестность точки $\vec{a}$
Пусть: $\vec{a} \in \mathbb{R}^n, \; \varepsilon > 0$

::: {layout-ncol="2"}

[1] $\varepsilon$ окрестность точки $\vec{a}$:	
$$
{K} _ \varepsilon \left( \vec{a} \right) = \lbrace \vec{x} \in \mathbb{R} \; | \; \| \vec{x} - \vec{a} \| < \varepsilon \rbrace
$$

[2] Проколотая $\varepsilon$ окрестность точки $\vec{a}$:	
$$
\dot{K} _ \varepsilon \left( \vec{a} \right) = \lbrace \vec{x} \in \mathbb{R} \; | \; 0 < \| \vec{x} - \vec{a} \| < \varepsilon \rbrace \Leftrightarrow {K} _ \varepsilon  \lbrace \vec{a} \rbrace \diagdown \lbrace \vec{a} \rbrace
$$

:::
	
#### Определение 3: Предельная точка
Пусть: $X \subset \mathbb{R}^n$ и $\vec{a} \in \mathbb{R}^n$\
$\vec{a}$ - предельная точка множества $X$ если: $\forall \varepsilon > 0 \; \dot{K}_\varepsilon \left( \vec{a} \right) \cup X \neq \emptyset$

	
#### Определение 4: Предел функции нескольких пременных
Пусть: $X \subset \mathbb{R}^n$, $\vec{a} \in \mathbb{R}^n$, $\vec{a}$ - предельная точка $X$, $f: X \to \mathbb{R}$ и $\vec{b} \in \mathbb{R}$\
$b$ называется пределом $f$ в точке $\vec{a}$ или при $\vec{x} \to \vec{a}$ если:
$$
\forall \varepsilon > 0  \; \exists \delta > 0 \; \; \forall \vec{x} \in \dot{K}_\delta \left( \vec{a} \right) \cap X \; \; f \left( \vec{x} \right) \in K_\varepsilon \left( b \right)
$$
Обозначается:
$$
\lim_{\vec{x} \to \vec{a}} f(\vec{x}) = b
$$

:::::: {.callout-note}
## Примечание 1
Для пределов функции нескольких переменных остаются справедливыми все основные свойства, операции, а также понятие “о” маленькое.	
$$
f ( \vec{x} ) = o ( g ( \vec{x} ) )
\Leftrightarrow
\lim_{\vec{x} \to \vec{a}} \frac{f(\vec{x})}{g(\vec{x})} = 0
$$
:::


#### Определение 5: Предел функции из $\mathbb{R}^n$ в $\mathbb{R}^m$
$X \subset \mathbb{R}^n$, $\vec{a} \in \mathbb{R}^n$, $\vec{a}$ - предельная точка $X$, $f: X \to \mathbb{R}$ и $\vec{b} \in \mathbb{R}^m$.

::: {layout-ncol="2"}

Предел:
$$
\lim_{\vec{x} \to \vec{a}} f(\vec{x}) = \vec{b}
$$

где 
$$
\vec{b} = 
\begin{pmatrix}
b_1 \\
b_2  \\
\vdots \\
b_m 
\end{pmatrix}
\in \mathbb{R}^m
$$

:::

Cуществует если:	
$$
\lim_{\vec{x} \to \vec{a}} f_k(\vec{x}) = b_k
\;\;
k=1,2,...,m
$$

	
#### Определение 6: Неприрывность функции из $\mathbb{R}^n$ в $\mathbb{R}^m$
Пусть: $X \subset \mathbb{R}^n$, $\vec{a} \in X$, $\vec{a}$ - предельная точка $X$, $f: X \to \mathbb{R}$\
Если 
$$
\lim_{\vec{x} \to \vec{a}} f(\vec{x}) = f(\vec{a})
$$

Функция называется непрерывной в точке $\vec{a}$. Если функция непрерывна в каждой точке $X$, то говорят, что $f$ непрерывна на $X$.
	
:::::: {.callout-note}
## Примечание 2
Для непрерывных функций нескольких переменных операции с ними и свойства остаются такими же. 
:::
