---
title: "Параграф XXI: Дифференциируемость функции нескольких переменных"
---
`Лекция от 03.02.2025`

#### Определение 1: Дифференциируемость функции нескольких переменных

::: {layout-ncol="2"}
Пусть:\
$X \subset \mathbb{R}^n$\
$f: X \rightarrow \mathbb{R}$\
$\vec x_0$ - предельная множества $X$

$\vec x_0 = \begin{pmatrix} x_{01} \\ x_{02} \\ \vdots \\ x_{0n} \end{pmatrix}$
::: 
Говорят, что $f$ - дифференциируема в $\vec x_0$ если $\exists A = \begin{pmatrix} a_1 & a_2 & \dots & a_n\end{pmatrix}$ -- матрица $\left( 1 \times n \right)$, такая, что:
$$
f\left(\vec x\right) = f\left(\vec x_0\right) + A\left(\vec x - \vec x_0\right) + o\left(|| \vec x - \vec x_0||\right)
$$

Или подробнее через определение Евклидовой нормы и учитывая, что:	
$$
\vec{x} - \vec{x_0} =
\begin{pmatrix}
x - x_{10} \\
x - x_{20} \\
\vdots \\
x - x_{n0}
\end{pmatrix}
$$

Следует:
	
$$
\begin{multline}
f(x_1, x_2, \dots, x_n) = f(x_{01}, x_{02}, \dots, x_{0n}) + \\
a_1(x_1-x_{10}) + a_2(x_2-x_{20}) + \dots + a_n(x_n-x_{n0}) + \\
+ o\left( \sqrt{(x_1-x_{10})^2 + (x_2-x_{20})^2 + \dots + (x_n-x_{n0})^2} \right)
\end{multline}
$$

И для частного случая с двумя переменными
	
$$
f(x, y) = f(x_0, y_0) + 
a_1(x-x_0) + a_2(y-y_0) +
o\left(\sqrt{(x-x_0)^2 + (y-y_0)^2}\right)
$$

#### Определение 2: Частные производные

::: {layout-ncol="2"}
Пусть:\
$X \subset \mathbb{R}^n$\
$f: X \to \mathbb{R}$\
$\vec{x_0}$ - предельная точка множества $X$

$\vec{x_0} = \begin{pmatrix} x_{10} \\ x_{20} \\ \vdots \\ x_{n0} \end{pmatrix} \in X$
:::

Положим: $x_2 = x_{20}, x_3 = x_{30}, \dots, x_n = x_{n0}$ и рассмотрим функцию: $f_1(x_1) = f(x_1, x_{20}, \dots, x_{n0})$\
Если эта функция одного переменного имеет производную в $x_{10}$, то эта производная называется частной производной по $x_{1}$ в точке $\vec{x_0}$ и бозначается:
$$
\frac{\partial f}{\partial x_1}(\vec{x}_0)
$$

То есть: $\frac{\partial f}{\partial x_1}(\vec{x}_0) = f_1'(x_{10})$, aналогично для $x_k, \; k=1,2, \dots,n$\
Таким образом мы будто фиксируем всё, кроме $x_k$. А следовательно производная получается функции одной переменной и все правила дифференцирования справедливы - сложение, вычитание, суперпозиция и т.д.

#### Определение 3: Производная функции нескольких переменных
Пусть: $X \subset \mathbb{R}^n$, $\vec{x_0} \in X$, $\vec{x_0}$ - предельная точка множества $X$, $f: X \to \mathbb{R}$, а также пусть у $f$ существуют все частные производные в точке $\vec{x_0}$, то такая матрица строка называется производной $f$ в $\vec{x_0}$:	
$$
\begin{pmatrix}
\frac{\partial f}{\partial x_1}(\vec{x}_0) &
\frac{\partial f}{\partial x_2}(\vec{x}_0)
&
\dots
&
\frac{\partial f}{\partial x_n}(\vec{x}_0)
\end{pmatrix}
=
f'(\vec{x}_0)
$$

А эта же, но __транспонированная__ матрица называется градиентом	
$$
\begin{pmatrix}
\frac{\partial f}{\partial x_1}(\vec{x}_0) \\
\frac{\partial f}{\partial x_2}(\vec{x}_0)
\\
\dots
\\
\frac{\partial f}{\partial x_n}(\vec{x}_0)
\end{pmatrix}
=
(f'(\vec{x}_0))^t = grad(f(\vec{x}_0)) = \nabla f(\vec{x}_0)
$$

	
#### Предложение 1
Если f дифференцируема в точке $\vec{x_0}$, то она непрерывна в $\vec{x_0}$

::: {.callout-warning}
### Важно
Но обратное не верно!!! Классным примером является функция [Вейерштрасса](https://ru.wikipedia.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F_%D0%92%D0%B5%D0%B9%D0%B5%D1%80%D1%88%D1%82%D1%80%D0%B0%D1%81%D1%81%D0%B0)
:::

Доказательство было в первом семестре матанализа для функции одной переменной. [(Сюда я потом обязательно вставлю ссылку на доказательство)]{.underline}
	
#### Теорема 1: Формула Тейлора для функции нескольких переменных
Если $f$ дифференцируема в точке $\vec{x_0}$, то справедливо: 
$$
f(\vec{x}) = f(\vec{x_0}) + f'(\vec{x}_0)(\vec{x}-\vec{x_0}) + o(\| \vec{x} - \vec{x_0} \|)
$$

Или подробнее:
$$
\begin{multline}
f(x_1, x_2, \dots, x_n) = f(x_{01}, x_{02}, \dots, x_{0n}) + \\
\sum_{k=1}^n{\frac{\partial f}{\partial x_k}(x_{01}, x_{02}, \dots, x_{0n})} + \\
o\left( \sqrt{(x_1-x_{10})^2 + (x_2-x_{20})^2 + \dots + (x_n-x_{n0})^2} \right)
\end{multline}
$$

*Получается формула Тейлора!*

##### Доказательство
По [определению 1](#определение-1-дифференциируемость-функции-нескольких-переменных) справедливо:	
$$
f(\vec{x}) = f(\vec{x_0}) + 
A(\vec{x}-\vec{x_0}) + 
o(\| \vec{x} - \vec{x_0} \|)
$$

Или подробно:	
$$
\begin{multline}
f(x_1, x_2, \dots, x_n) = f(x_{01}, x_{02}, \dots, x_{0n}) + \\
a_1(x_1-x_{10}) + a_2(x_2-x_{20}) + \dots + a_n(x_n-x_{n0}) + \\
o\left( \sqrt{(x_1-x_{10})^2 + (x_2-x_{20})^2 + \dots + (x_n-x_{n0})^2} \right)
\end{multline}
$$

Положим: $x_2 = x_{20}, x_3 = x_{30}, \dots, x_n = x_{n0}$.	Тогда (много сокращается из-за равенства):
$$
f(x_1, x_{02}, \dots, x_{0n}) = f(x_{01}, x_{02}, \dots, x_{0n}) + 
a_1(x_1-x_{10}) + 
o\left(\sqrt{(x_1-x_{10})^2}\right)
$$

По [определению 2](#определение-2-частные-производные):	
$$
f_1(x_1) = f_1(x_{01}) + 
a_1(x_1-x_{10}) + 
o\left(\sqrt{(x_1-x_{10})^2}\right)
$$

И по одному из доказательств первого семестра получается, что:
$$
\begin{align*}
a_1 = f'_1\left( x_{10} \right) \\
a_1 = \frac{\partial f}{\partial x_1}\left(\vec{x_0}\right)
\end{align*}
$$

Аналогично для $a_k, \; k=1,2,\dots,n$. Следовательно:
$$
A=
\begin{pmatrix}
\frac{\partial f}{\partial x_1}(\vec{x}_0) &
\frac{\partial f}{\partial x_2}(\vec{x}_0)
&
\dots
&
\frac{\partial f}{\partial x_n}(\vec{x}_0)
\end{pmatrix}
=
f'(\vec{x}_0)
$$

Значит верна формула Тейлора. $\blacksquare$
	
::: {.callout-note}
## Замечание 2
Для функции двух переменных формула Тейлора первого порядка выглядит:
$$
f(x,y) = f(x_0, y_0)
+ 
\frac{\partial f}{\partial x}(x_0, y_0)(x-x_0) 
+ 
\frac{\partial f}{\partial y}(x_0, y_0)(y-y_0) 
+
o\left( \sqrt{(x-x_0)^2 + (y-y_0)^2} \right)
$$
:::
	
`Лекция от 10.02.2025`

#### Теорема 2: достаточные условия дифференциируемости функции $n$ переменных
Пусть: $X\in \mathbb{R}^n, \; f : X \rightarrow \mathbb{R}$\
Если  все частные производные существуют в некоторой $K_\varepsilon (M_0)$ и неприрывны в $M_0$, то $f$ дифференциируема в $M_0$. Без доказательства. 

#### Следствие 1: достаточное условие дифференциируемости функции двух переменных
Пусть: $X\in \mathbb{R}^2, \; f : X \rightarrow \mathbb{R}$\
Если $\frac{\partial f}{\partial x}$ и $\frac{\partial f}{\partial y}$ существуют в некоторой $K_\varepsilon ( M_0)$, $M_0(x_0,y_0)$ и неприрывны в $M_0$, то $f$ дифференциируема в $M_0$.