---
title: "Электрическое Поле"
date: "12 07 2025"
---

Любой заряд является источником электромагнитного поля, распространяющегося в вакууме со скоростью света. В случае неподвижных зарядов такое поле называется электростатическим и его основное свойство заключается в том, что на всякий помещённый в него заряд действует сила. Электростатическое поле описывается двумя величинами: потенциалом и напряжённостью. Напряжённость - силовая характеристика, потенциал - энергетическая.

#### Напряжённость
Напряжённость имеет размерность $[E] = В/м$ и равна $\vec{E} = \frac{\vec{F}}{q}$, где $q$ - пробный заряд не сильно искажающий общее поле, то есть напряжённость показывает куда и с какой силой поле будет действовать на точечный заряд. Для точечного заряда уравнение напряжённости электростатического поля будет выглядеть так:

::: {.columns}
::: {.column}
$$
\vec{E} = \frac{1}{4 \pi \, \varepsilon_0 } \cdot \frac{q}{\varepsilon \, r^3} \vec{r}
$$
:::
::: {.column}
где $\vec{r}$ - вектор от тела к точке наблюдения.
:::
:::

Электростатическое поле можно изображать с помощью силовых линий. Их рисуют по очень простым правилам:

1. Они идут от плюса к минусу
2. Чем больше модуль $\vec{E}$ тем они гуще
3. Касательные к ним должны быть $\vec{E}$

Для напряжённости электростатического поля совершенно спокойно работает принцип суперпозиции: напряжённость поля системы зарядов равна векторной сумме напряжённость полей, которые создавал бы каждый из зарядов системы в отдельности, $\vec{E} = \sum{\vec{E}_i}$. Отсюда также следует, что и силы, от каждого заряда также будут подчиняться принципу суперпозиции  $\vec{F} = \sum{\vec{F}_i}$.
