---
title: "Энергия электростатического поля и системы зарядов"
date: "14 07 2025"
---

#### Уединённый проводник

Рассмотрим уединённый проводник. У него в какой-то момент есть заряд $q$ и потенциал его определяется через $\varphi = \frac{q}{C}$. Для приобретения потенциала его надо для начала зарядить. Изменение энергии уединённого проводника
$$
W = \int_0^W{dW} = \int_0^q{\varphi dq} = \int_0^q{\frac{q}{C}dq} = \frac{q^2}{2C} = \frac{q\varphi}{2} = \frac{C \varphi^2}{2}
$$


#### Несколько зарядов

Теперь рассмотрим два заряда $q_1$ и $q_2$. Их потенциальная энергия
$$
W = \frac{kq_1 q_2}{r_{12}}
$$

Что можно записать в другом виде
$$
W = q_1\varphi_{12} = q_2\varphi_{21}
$$

То есть с помощью потенциалов, создаваемых одним проводником в точке другого. Таким образом энергию можно записать в виде полусуммы
$$
W = \frac{1}{2} \left({q_1\varphi_{12} + q_2\varphi_{21}}\right)
$$

Легко увидеть, что для больших систем зарядов энергия будет
$$
W = \frac{1}{2}\sum_{ij}{q_i\varphi_{ij}}
$$

Если $i = j$, то получается собственная энергия и её можно вынести и для системы тел с конечными размерами всё норм. Ломается наша формула только для точечных зарядов, хотя даже и не полностью, так как потенциал заряда создаваемый им на самом себе просто ноль, то сумма внутренних энергий зарядов просто обратится в ноль
$$
W = \frac{1}{2} \sum_{i \neq j}{q_i\varphi_{ij}} + \frac{1}{2} \sum_{i}{q_i\varphi_{ii}}
$$

Короче здесь мы умножаем заряд тела на потенциал, созданный другими зарядами в его положении. Также это можно записать с помощью ёмкостей
$$
W = \frac{1}{2}\sum_{ij}{q_i\varphi_{ij}} = \frac{1}{2}\sum_{i}{q_i}\sum_{j}{\varphi_{ij}}
$$

Сумму потенциалов, созданных всеми телами, на месте нашего, включая его, можно переобозначить
$$
\sum_{j}{\varphi_{ij}} = \varphi_i
$$

И тогда
$$
W = \frac{1}{2}\sum_{i}{q_i\varphi_{j}}
$$

А вспомнив, что $q_i = C_{ij}\varphi_j$ получается
$$
W = \frac{1}{2}\sum_{ij}{C_{ij}\varphi_{j}\varphi_{i}}
$$

Это есть потенциальная энергия системы