---
title: "Немного теории множеств"
date: "10 08 2025"
---

### Определение

**Множество** -- совокупность объектов, обладающих общим свойством. Множеством могут быть все машины на планете у которых сломался правый задний датчик АБС или все натуральные числа. Обычно множества обозначают большими латинскими символами $A$, $B$, $C$ и т.д.

Создатель теории множеств -- [Георг Кантор](https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BD%D1%82%D0%BE%D1%80,_%D0%93%D0%B5%D0%BE%D1%80%D0%B3), интересно, что когда он её представил, много математиков того времени были с ним совсем не согласны в том, что это полезно, а кто-то даже называл его научным шарлатаном. Ну да ту самую теорию на которой держится вся современная математика тогда принимали со скрежетом.


### Операции над множествами

Существуют операции которые мы можем к ним применять

#### Объединение 
$A \cup B$ -- множество содержащее все элементы и из $A$ и из $B$

> Чтобы запомнить символ этой операции я обычно представляю, как два множества будто вместе наливают в один стакан $\cup$

#### Пересечение
$A \cap B$ -- множество элементов, которые есть как в $A$ так и в и $B$

> А здесь наоборот, если представить два множества как, например, две кучки каких-то круп, то мы одним стаканом $\cap$ накрываем пересекающиеся их части

#### Разность
$A \setminus B$ -- множество элементов $A$, что не содержатся в $B$

> Ну здесь, мне кажется ни с чем не перепутать

Также можно обозначить вычитание определённого элемента из множества $A \setminus \lbrace x \rbrace$

> К слову как я понял, окружая элемент фигурными скобками мы будто записываем его как множество из одного элемента, потому вычитать можно только множества? Ну в общем для операций объединения, пересечения (хотя пересекать множество с одним единственным элементом странно) и вычитания так принято

#### Декартово произведение
$A \times B$ -- множество упорядоченных всех пар элементов из $A$ и $B$. Упорядоченных значит, что $(x;y) \neq (y;x)$
Или по другому $A \times B = \lbrace (x;y) \; \vert \; x \in A \; \wedge \; y \in B \rbrace$

### Связи множеств и не множеств

Вы вероятно уже заметили несколько новых символов, так вот

#### Принадлежность элемента множеству
Символом $\in$ обозначают то, что определённый элемент содержится в определённом множестве например $\xi \in Z$ -- элемент $\xi$ принадлежит множеству $Z$.

> А вот здесь фигурные скобки не нужны, да, потому что тут принадлежность

#### Подмножество
Символом $\subset$ обозначают, что одно множество полностью содержится в другом. $Q \subset D$ множество $Q$ подмножество $D$

#### Равенство 
Мне кажется, что это достаточно очевидная связь. $A = W$ -- множество $A$ равно множеству $W$, то есть каждый элемент множества $A$ равен каждому в множестве $W$
> Интересный факт заключается в том, что из равенства множеств следует то, что оба они подмножества друг друга

#### Пустое множество
Существует особый символ $\emptyset$, означающий пустое множество, вы вероятно его встречали в обозначении отсутствия вещественных корней уравнения.

### Границы множеств 
Дадим несколько определений в строгой форме, который потом пригодятся

#### Верхняя граница множества
Число $k \in \mathbb{R}$ называется верхней границей множества $X$, если $\forall x \in X \; | \; x \le k$

#### Нижняя граница множества
Число $l \in \mathbb{R}$ называется нижней границей множества $X$, если $\forall x \in X \; | \; x \ge l$

>Интересно, но границей может называться число хоть сколько удалённое от нашего множества, главное чтобы условие выполнялось

#### Супремум
Наименьшая верхняя граница множества $X$ называется супремумом и обозначается $\sup X$.

#### Инфимум
Наибольшая нижняя граница множества $X$ называется инфимумом и обозначается $\inf X$. 

При том `супремум` и `инфимум` всегда определены, при том они не обязательно должны принадлежать множеству или быть конечны. Например у последовательности чисел вида $\frac{1}{n}, n \in \mathbb{N}$ инфимумом будет 0, при этом он не входит в само множество.

В общем как-то так

:::{layout-ncol="2"}
$$
\sup = 
\begin{cases}
k \in \mathbb{R}, \; \text{если} \; X \; \text{ограниченно сверху} \\
+\infty, \; \text{если} \; X \; \text{неограниченно сверху} 
\end{cases}
$$

$$
\inf = 
\begin{cases}
l \in \mathbb{R}, \; \text{если} \; X \; \text{ограниченно снизу} \\
-\infty, \; \text{если} \; X \; \text{неограниченно снизу} 
\end{cases}
$$
:::

### Точки в множестве

#### Окрестность точки
$\delta$ окрестность точки $x_0$ определяется так
$$
K_\delta(x_0) = (x_0 - \delta ; x_0 + \delta),\; \delta > 0
$$

#### Проколотая окрестность точки
Проколотая $\delta$ окрестность точки $x_0$ определяется как обычная окрестность, но без точки вокруг которой она
$$
\overset{\circ}K_\delta(x_0) = K_\delta(x_0) \setminus \lbrace x_0 \rbrace > 0
$$

#### Предельная точка
Точку $x_0 \in X$ называют предельной точкой множества $X$, если 
$$
\forall \delta > 0 \; | \; \overset{\circ}K_\delta(x_0) \cap X \neq \emptyset
$$

То есть точка не обязательно принадлежит множеству, но окрестность её всегда должна пересекать его.

##### Изолированная
Точку $x_0 \in X$ называют изолированной точкой множества $X$, если 
$$
\exists \delta > 0 \; | \; \overset{\circ}K_\delta(x_0) \cap X = \emptyset
$$

Интересный пример снова находится в уже известной нам последовательности $\frac{1}{n}, n \in \mathbb{N}$. Здесь каждый элемент -- изолированная точка, так как если для каждого $n$ взять $\delta < 1$, то ни одна из точек множества не попадёт в $\overset{\circ}K_\delta(\frac{1}{n})$ окрестность. При этом 0 является точкой предельной, потому что для любого $\delta > 0$ найдётся число попадающее в $\overset{\circ}K_\delta(0)$

### Функции в теории множеств
Функция -- отображение(закон/правило) по которому для $\forall x \in X$ сопоставляется __единственный__ $y \in Y$. При том $x$ называют прообразом, а соответствующий ему $y$ образом. Обычно в контексте того, какое множество функция отображает на какое её обозначают
$$
f: X \rightarrow Y
$$

Ну или можно немного иначе
$$
X \overset{f}\rightarrow Y
$$

#### Область определения
Для функции область определения -- множество прообразов
$$
D(f) = X
$$

#### Область значений
Для функции область определения -- множество образов
$$
E(f) = Y
$$

Важно, что область определения может быть больше области значений, и одному образу может соответствовать несколько прообразов, простой пример -- тригонометрические функции $\sin$ и $\cos$. Область определения у них -- все вещественные числа, при этом их значения ограничены 1 и -1