---
title: "Основные методы интегрирования"
date: "11 07 2025"
---
`Лекция 1 (07.02.2025)`

#### Метод замены переменной
Если $f(x)$ непрерывна, $F(x)$ - её первообразная, полагая что $x = \varphi(t)$, где $\varphi(t)$ - непрерывно дифференцируема, получаем:
$$
\int f(x)dx = \left[ x = \varphi(t) \right] = \int f(\varphi(t))d\varphi(t) = \int f(\varphi(t))\varphi'(t)dt = F(\varphi(t)) + C
$$

Но чаще на практике этой формулой пользуются иначе, а именно, функции в интеграле “вносят под дифференциал” или после замены “выносят”:
$$
\varphi'(t)dt = d\varphi(t)
$$

##### Пример
$$
\int \sin(x^2)x\,dx = \int \frac{1}{2} \sin(x^2) \cdot 2x\,dx = \frac{1}{2} \int \sin(x^2)dx^2 = -\frac{1}{2} \cos(x^2) + C
$$

В данном случае мы “внесли” $2x$ под дифференциал, так как $(x^2)' = 2x$.

##### Доказательство
Заметим, что результат формулы очень похож на производную сложной функции, собственно через неё и докажем. Пусть $F(x)$ -- первообразная для $f(x)$, тогда:
$$
\left( F(\varphi(t)) \right)' = F'(\varphi(t)) \cdot \varphi'(t) = f(\varphi(t)) \cdot \varphi'(t)
$$

Это показывает, что $F(\varphi(t))$ является первообразной для $f(\varphi(t))\varphi'(t)$.


#### Метод интегрирования по частям

##### Формула интегрирования по частям
Если $v(x)$ и $u(x)$ - дифференцируемые функции, то справедливо:
$$
\int u(x) v'(x) \, dx = u(x) v(x) - \int v(x) u'(x) \, dx
$$

Хотя на практике проще пользоваться видом:
$$
\int u \, dv = u \cdot v - \int v \, du
$$

##### Доказательство
Не трудно заметить, что на самом деле это всего-лишь переставленное местами дифференцирование произведения функций:
$$
(u(x)v(x))' = u'(x)v(x) + u(x)v'(x)
$$

Если проинтегрировать обе части, то получается, что:
$$
u(x)v(x) = \int u'(x)v(x) \, dx + \int u(x)v'(x) \, dx
$$

И если после переставить:
$$
\int u(x)v'(x) \, dx = u(x)v(x) - \int u'(x)v(x) \, dx
$$
