---
title: "Закон Ома, Сопротивление"
---

#### Формально про скорость

Заряженные частицы в электрическом поле под действием силы с его стороны двигаются с ускорением, но с другой стороны мы знаем, что в общем заряды двигаются с постоянной скоростью, а значит должна существовать ещё одна сила сопротивления уравновешивающая дело. При том уравновешивающая сила должна зависеть от скорости.
Пусть в нашей простейшей модели сила сопративаления будет линейно зависеть от скорости через коэффициент $\text{ae}$, тогда

::: {.columns}
::: {.column}
$$
F = q_1 \, E = F_r (v) = \text{ae} \, v
$$
:::
::: {.column}
$$
v = \frac{q_1}{\text{ae}}E
$$
:::
:::

Получившийся новый коэффициент можно обозначить за одну букву
$$
\frac{q_1}{\text{ae}} = \frac{\langle v \rangle}{E} = \mu
$$

Здесь $\langle v \rangle$ - средняя дрейфовая скорость (как раз та, что совсем [маленькая](p1_direct_current.qmd#скорость-частиц)), $\mu$ обозвали п**одвижность носителей заряда**.

Также добавлю, что есть понятие **удельная электропроводность полупроводника**
$$
\sigma = \frac{j}{E}
$$

Ну а теперь используем полученную информацию и получаем, что 
$$
v = \mu \, E
\quad
\text{и}
\quad
j = q_1\,n\,\mu E
$$

Откуда переобозначив выводим 
$$
j = \gamma \,E
$$

Ну и так как скорость сонаправленна напряженности, можно перейти к векторам
$$
\vec v = \mu \, \vec E
\quad
\text{и}
\quad
\vec i = \gamma \, \vec E
$$

Что на самом деле -- **закон Ома в дифференциальной форме**! Итак. 

#### Закон Ома в дифференциальной форме
$$
\vec j = \gamma \, \vec E
$$

Где $\gamma$ -- удельная проводимость. Ей вводят обратную величину $\rho = \frac{1}{\gamma}$ -- удельное сопротивление.

А теперь покажем, что это реально закон Ома. И интегрируя выражение по площади сечения проводника
$$
I = \int_S {\vec j \, d\vec S} = \int_S {\gamma \, \vec E\, d\vec S}
$$

И к тому же если у нас в кусочке проводника не меняются свойства(проводимость, площадь и т.д.), то тогда у него внутри одно и то же поле $\vec E$. А значит разность потенциалов
$$
U = \int {\vec E\, d\vec l} \;\; [\vec E = const] \implies U = E\,l
$$

И получается, что
$$
I = \int_S {\vec j \, d\vec S} = \int_S {\gamma \, \vec E\, d\vec S} = \int_S {\gamma \, \frac{U}{l}\, dS_\perp}
$$

Далее можно всё лишнее как константы вынести и получится
$$
I = \gamma \, \frac{U}{l}\, S = \frac{U}{R} = Y \, U
$$

К тому же можно понять, что
$$
R = \frac{l}{\gamma\,S} = \frac{\rho \, l}{S}
$$

Но это справедливо только когда удельная проводимость/сопротивление и площадь проводника не меняется. А если это не так, то на этапе с заменой напряжённости на напряжение и длину, нужно взять не интеграл, а производную *(я сам плохо понял этот `мув`)*

$$
U = \int {\vec E\, d\vec l} \; \implies \frac{dU}{dl} = dE
$$

И тогда сопротивление *(поэтому просто запомните это, да собственно оно и логично)*
$$
R = \int{\frac{\rho\,dl}{S}}
$$
Хотя, по хорошему тип без разницы по чему интегрировать, если всё правильно поставить. поэтому да.

