---
title: "Катастрофа Теории Друды-Лоренца"
---

#### Движение электронов в металле
Они в металле движутся в среднем с одной скоростью и мы можем определить её максимальное значение. Она равна ускорению действующему на электрон умноженному на время между столкновениями, и ускорение это генерируется каким-то внешним полем
$$
v_{max} = a\,t = \frac{-e\,E}{m_e}\, t
$$

С другой стороны время межу соударениями на самом деле определяется не дрейфовой скоростью, а скоростью теплового движения, так как мы ранее уже [заметили](p1_direct_current.qmd#скорость-частиц) насколько она больше. Поэтому время можно заменить на длину свободного пробега делённую на тепловую скорость
$$
v_{max} = \frac{-e\,E}{m_e}\cdot \frac{\lambda}{v_t}
$$

Определим среднюю скорость, она будет при равноускоренном движении просто половиной от максимальной
$$
v = \frac{-e\,E\,\lambda}{2\,m_e\,v_t}
$$

Тогда плотность тока
$$
j = -e\,n\,v= \frac{e^2\,\lambda\,n}{2\,m_e\,v_t} \cdot E
$$

Это же закон Ома в дифференциальной форме!!! Ну а то, что у нас перед $E$ -- просто удельная проводимость или же, в обратную сторону, удельное сопротивление

::: {.columns}
::: {.column}
$$
\gamma = \frac{e^2\,\lambda\,n}{2\,m_e\,v_t}
$$
:::
::: {.column}
$$
\rho = \frac{2\,m_e\,v_t}{e^2\,\lambda\,n}
$$
:::
:::

И эта формула работает! И иногда даже норм, но не для всех металлов. Алюминий `топ`, железо `похуже`, но тоже нормаc. В качестве $\lambda$ можно взять расстояние между атомами или что-то такое. А медь и серебро дают **не верный** результат, если $\lambda$ взять как межатомное расстояние. Сопоставимый результат получается если установить $\lambda$ раз в **10 больше** расстояния между атомами. А если температура падает, то это $\lambda$ начинает расти, как будто электроны практичеаски перестают сталкиваться с атомами.

Мы уже ранее [посчитали](p1_direct_current.qmd#скорость-частиц), что средняя тепловая скорость пропорциональна корню из температуры
$$
v_t = \sqrt{\frac{3\,k\,T}{m_e}} \sim \sqrt{T}
$$

Но в экспериментах сопротивление
$$
R = \frac{\rho\,l}{S}
$$

Зависит иначе
$$
R = R_0\cdot \left( 1+ \alpha \, \Delta T\right)
$$

Или

$$
\rho = \rho_0\cdot \left( 1+ \alpha \, \Delta T\right)
$$

А если через абсолютную температура записать, получится, что сопротивление зависит линейно от температуры, а не корнево:
$$
\rho \sim T
$$

Да ещё и длинна свободного пробега большая получается!! Нехорошооо. Это не хорошо получается совсем не хорошо и значит, что всё что мы написали ранее не верно, а именно теория `Друды-Лоренца`. И для того, чтобы правильно описать электропроводность металлов, приходится лезть в квантовую механику, и она уже много лучше описывает и предсказывает реальность. А до этого ещё далеко